name: Run Verilator
description: Run Verilator at a specific version
branding:
  icon: "cpu"
  color: "purple"

inputs:
  version:
    description: The version of Verilator to use
    required: false
    default: latest
  arguments:
    description: The arguments to pass to Verilator
    required: true

runs:
  using: node20
  main: dist/index.js