name: Run Verilator
description: Run Verilator at a specific version
branding:
  icon: "cpu"
  color: "purple"

inputs:
  version:
    description: The version of Verilator to use
    required: false
    default: latest
  arguments:
    description: The arguments to pass to Verilator
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if version is supported
      shell: bash
      run: |
        HTTP_CODE=$(curl -L -s -o /dev/null -w "%{http_code}" 'https://search.devbox.sh/v2/resolve?name=verilator&version=${{ inputs.version }}' -H 'Accept: application/json')
        if [ "$HTTP_CODE" -ne "200" ]; then
          echo "Verilator version ${{ inputs.version }} is not supported"
          exit 1
        fi
    - name: Check if devbox is installed
      id: check_devbox
      shell: bash
      run: |
        # Check if the file exists using the test command
        if [ -f "~/.local/bin/devbox" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    - name: create devbox project folder
      if: ${{ steps.check_devbox.outputs.exists == 'false' }}
      shell: bash
      run: |
        echo "devbox_project_path=$(mktemp -d)" >> $GITHUB_ENV
    - name: create devbox.json (dummy, only for the install)
      if: ${{ steps.check_devbox.outputs.exists == 'false' }}
      shell: bash
      run: |
        echo '{
          "packages": {
          }
        }' > $devbox_project_path/devbox.json
    - name: Install devbox
      if: ${{ steps.check_devbox.outputs.exists == 'false' }}
      uses: jetify-com/devbox-install-action@v0.12.0
      with:
        project-path: $devbox_project_path
        enable-cache: 'true'
    - name: Add devbox to PATH
      if: ${{ steps.check_devbox.outputs.exists == 'true' }}
      shell: bash
      run: |
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
    - name: Add verilator
      shell: bash
      run: |
        . <(devbox global shellenv)
        devbox global add verilator@${{ inputs.version }}
    - name: Run verilator
      shell: bash
      run: |
        . <(devbox global shellenv)
        verilator ${{ inputs.arguments }}
    - name: Clean up
      shell: bash
      run: |
        . <(devbox global shellenv)
        devbox global rm verilator
