on: [push, workflow_dispatch]

jobs:
  verilator-version:
    name: Verilator version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verilator version
        uses: ./
        with:
          arguments: '--version'
      - name: Verilator version 
        uses: ./
        with:
          version: 5.038
          arguments: '--version'
      - name: Verilator version
        uses: ./
        with:
          version: 5.034
          arguments: '--version'
      - name: Verilator version (expected fail)
        continue-on-error: true
        uses: ./
        with:
          version: 5.037
          arguments: '--version'

  verilator-calls:
    name: Verilator calls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verilator lint as argument
        uses: ./
        with:
          arguments: '--lint-only testdata/A.v'
      - name: Verilator lint as argument
        uses: ./
        with:
          arguments: '--lint-only A.v'
          working-directory: testdata
      - name: Verilator lint as run
        uses: ./
        with:
          run: 'verilator --lint-only A.v'
          working-directory: testdata
      - name: Verilator lint as own action
        uses: ./
        with:
          lint-files: 'testdata/A.v'

  verilator-lint:
    name: Verilator lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verilator lint A
        uses: ./
        with:
          lint-files: 'testdata/A.v'
      - name: Verilator lint B
        uses: ./
        continue-on-error: true
        with:
          lint-files: 'testdata/B.v'