on: [push, workflow_dispatch]

jobs:
  test:
    name: Verilator calls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verilator lint as argument
        uses: ./
        with:
          run: 'make'
          working-directory: testdata
